title: Deborah Hanus
tagline: ""
description:

url: http://dhanus.github.io 
baseurl: ""
paginate_path: "blog/page:num/"
permalink: blog/:title/

navigation:
- title: Blog
  url: /index.html
- title: About
  url: /about


markdown: kramdown
highlighter: rouge
gems: [jekyll-paginate]
paginate: 10


author:
   name: "Deborah Hanus"
   github: dhanus
   twitter: deborahhanus
   facebook: deborah.hanus
   email: dhanus@mit.edu
   linkedin: deborahhanus

google_analytics: ""
